CREATE TABLE species (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(50)  UNIQUE NOT NULL,
  description VARCHAR2(200)
);

CREATE TABLE event_type (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(50)  UNIQUE NOT NULL,
  points_reward NUMBER        NOT NULL,
  category      VARCHAR2(50)  NOT NULL
);

CREATE TABLE reward_action (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR2(50)  UNIQUE NOT NULL,
  points_value NUMBER        NOT NULL,
  description  VARCHAR2(200)
);

CREATE TABLE risk_level (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(50)  UNIQUE NOT NULL,
  description VARCHAR2(200),
  min_score   NUMBER        NOT NULL,
  max_score   NUMBER        NOT NULL
);

CREATE TABLE tutor (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR2(100) NOT NULL,
  role          VARCHAR2(20) DEFAULT 'TUTOR' NOT NULL,
  email         VARCHAR2(100) UNIQUE NOT NULL,
  phone         VARCHAR2(20),
  password_hash VARCHAR2(255) NOT NULL,
  created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE address (
  id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tutor_id  NUMBER        NOT NULL,
  street    VARCHAR2(200) NOT NULL,
  city      VARCHAR2(100) NOT NULL,
  state     VARCHAR2(50)  NOT NULL,
  zip_code  VARCHAR2(10)  NOT NULL,
  CONSTRAINT fk_address_tutor FOREIGN KEY (tutor_id) REFERENCES tutor(id)
);

CREATE TABLE clinic (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR2(100) NOT NULL,
  address    VARCHAR2(200),
  phone      VARCHAR2(20),
  cnpj       VARCHAR2(18)  UNIQUE,
  created_at TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pet (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tutor_id   NUMBER        NOT NULL,
  species_id NUMBER        NOT NULL,
  name       VARCHAR2(100) NOT NULL,
  breed      VARCHAR2(50),
  birth_date DATE,
  weight     NUMBER(5,2),
  created_at TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pet_tutor   FOREIGN KEY (tutor_id)   REFERENCES tutor(id),
  CONSTRAINT fk_pet_species FOREIGN KEY (species_id) REFERENCES species(id)
);

CREATE TABLE plan (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id        NUMBER        NOT NULL,
  name             VARCHAR2(100) NOT NULL,
  description      VARCHAR2(200),
  price            NUMBER(10,2)  NOT NULL,
  duration_days    NUMBER        NOT NULL,
  points_per_event NUMBER        DEFAULT 1 NOT NULL,
  -- multiplicador: plano premium pode dar 2x pontos por evento
  CONSTRAINT fk_plan_clinic FOREIGN KEY (clinic_id) REFERENCES clinic(id)
);

CREATE TABLE subscription (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id     NUMBER       NOT NULL,
  plan_id    NUMBER       NOT NULL,
  start_date DATE         NOT NULL,
  end_date   DATE,
  status     VARCHAR2(20) NOT NULL,
  -- status: 'ATIVO', 'ENCERRADO', 'CANCELADO'
  created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sub_pet  FOREIGN KEY (pet_id)  REFERENCES pet(id),
  CONSTRAINT fk_sub_plan FOREIGN KEY (plan_id) REFERENCES plan(id)
);

CREATE TABLE health_event (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id        NUMBER        NOT NULL,
  event_type_id NUMBER        NOT NULL,
  clinic_id     NUMBER,
  description   VARCHAR2(200),
  event_date    DATE          NOT NULL,
  status        VARCHAR2(20)  NOT NULL,
  -- status: 'REALIZADO', 'PENDENTE', 'CANCELADO'
  created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_he_pet        FOREIGN KEY (pet_id)        REFERENCES pet(id),
  CONSTRAINT fk_he_event_type FOREIGN KEY (event_type_id) REFERENCES event_type(id),
  CONSTRAINT fk_he_clinic     FOREIGN KEY (clinic_id)     REFERENCES clinic(id)
);

CREATE TABLE reward_point (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tutor_id         NUMBER        NOT NULL,
  reward_action_id NUMBER        NOT NULL,
  points           NUMBER        NOT NULL,
  reference_type   VARCHAR2(50),
  -- ex: 'HEALTH_EVENT', 'SUBSCRIPTION', 'CADASTRO_PET'
  reference_id     NUMBER,
  -- id do registro que gerou os pontos
  created_at       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rp_tutor  FOREIGN KEY (tutor_id)         REFERENCES tutor(id),
  CONSTRAINT fk_rp_action FOREIGN KEY (reward_action_id) REFERENCES reward_action(id)
);

CREATE TABLE partner_discount (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id        NUMBER        NOT NULL,
  partner_name     VARCHAR2(100) NOT NULL,
  category         VARCHAR2(50)  NOT NULL,
  -- categoria: 'RACAO', 'PETSHOP', 'MEDICAMENTO', 'CONSULTA'
  discount_percent NUMBER(5,2)   NOT NULL,
  CONSTRAINT fk_pd_clinic FOREIGN KEY (clinic_id) REFERENCES clinic(id)
);

CREATE TABLE coupon_template (
  id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_discount_id NUMBER       NOT NULL,
  title              VARCHAR2(100) NOT NULL,
  discount_value     NUMBER(10,2)  NOT NULL,
  discount_type      VARCHAR2(20)  NOT NULL,
  -- tipo: 'PERCENTUAL', 'VALOR_FIXO'
  points_required    NUMBER        NOT NULL,
  CONSTRAINT fk_ct_partner FOREIGN KEY (partner_discount_id) REFERENCES partner_discount(id)
);

CREATE TABLE coupon (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id     NUMBER       NOT NULL,
  code            VARCHAR2(50) UNIQUE NOT NULL,
  status          VARCHAR2(20) NOT NULL,
  -- status: 'DISPONIVEL', 'RESGATADO', 'EXPIRADO'
  expiration_date DATE,
  created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_coupon_template FOREIGN KEY (template_id) REFERENCES coupon_template(id)
);

CREATE TABLE redeem (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tutor_id    NUMBER    NOT NULL,
  coupon_id   NUMBER    NOT NULL,
  points_used NUMBER    NOT NULL,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_redeem_tutor  FOREIGN KEY (tutor_id)  REFERENCES tutor(id),
  CONSTRAINT fk_redeem_coupon FOREIGN KEY (coupon_id) REFERENCES coupon(id)
);

CREATE TABLE risk_score (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id        NUMBER    NOT NULL,
  score         NUMBER    NOT NULL,
  risk_level_id NUMBER    NOT NULL,
  calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rs_pet   FOREIGN KEY (pet_id)        REFERENCES pet(id),
  CONSTRAINT fk_rs_level FOREIGN KEY (risk_level_id) REFERENCES risk_level(id)
);